services:
  spring:
    image: 'user-service:latest'
    ports:
      - '8002:8002'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
